const fs = require('fs');
const routes = JSON.parse(fs.readFileSync('local_routes_data.json', 'utf8'));
const fareMatrix = JSON.parse(fs.readFileSync('local_fare_matrix.json', 'utf8'));
const distData = JSON.parse(fs.readFileSync('local_routes_distance.json', 'utf8'));
const busServices = JSON.parse(fs.readFileSync('local_bus_services.json', 'utf8'));

let out = '// AUTO-GENERATED by sync-from-xlsx.js — DO NOT EDIT\n';
out += '// Local bus route data, fare matrix, distance data, and bus services\n\n';
out += 'var LOCAL_ROUTES_DATA = ' + JSON.stringify(routes) + ';\n\n';
out += 'var LOCAL_FARE_MATRIX = ' + JSON.stringify(fareMatrix) + ';\n\n';
out += 'var LOCAL_ROUTES_DISTANCE = ' + JSON.stringify(distData) + ';\n\n';
out += 'var LOCAL_BUS_SERVICES = ' + JSON.stringify(busServices) + ';\n';

fs.writeFileSync('local_bus_data.js', out, 'utf8');
console.log('Generated local_bus_data.js:', (Buffer.byteLength(out) / 1024).toFixed(1) + 'KB');
