const LOCAL_STOP_EN = {
  "অরিজিনাল দশ": "Original 10",
  "অরিজিনাল-১০": "Original-10",
  "আগলা বাজার": "Agla Bazar",
  "আগারগাঁও": "Agargaon",
  "আজমপুর": "Azampur",
  "আজিমপুর": "Azimpur",
  "আজিমপুর (ঢাকেশ্বরী)": "Azimpur (Dhakeshwari)",
  "আটিবাজার": "Ati Bazar",
  "আনসার ক্যাম্প": "Ansar Camp",
  "আবুল হোটেল": "Abul Hotel",
  "আব্দুল্লাহপুর": "Abdullahpur",
  "আব্দুল্লাহপুর জেলখানা)": "Abdullahpur (Jailkhana)",
  "আমিন বাজার": "Amin Bazar",
  "আমুলিয়া স্টাফ কোয়ার্টার": "Amulia Staff Quarter",
  "আরামবাগ": "Arambagh",
  "আশুলিয়া": "Ashulia",
  "আশুলিয়া (ফ্যান্টাসি কিংডম)": "Ashulia (Fantasy Kingdom)",
  "আসাদ এভিনিউ": "Asad Avenue",
  "আসাদ গেট": "Asad Gate",
  "ইউবিএল": "UBL",
  "ইকুরিয়া": "Ekuria",
  "ইডেন কলেজ": "Eden College",
  "ইত্তেফাক": "Ittefaq",
  "ইপিজেড": "EPZ",
  "ইসলামপুর": "Islampur",
  "ইসিবি চত্ত্বর": "ECB Chattar",
  "ইসিবি মোড়": "ECB More",
  "ইস্টার্ন হাউজিং": "Eastern Housing",
  "উড়োজাহাজ ক্রসিং": "Urojahaj Crossing",
  "উত্তর বাড্ডা": "Uttar Badda",
  "উত্তরা": "Uttara",
  "উত্তরা (রাণীগঞ্জ)": "Uttara (Ranigonj)",
  "উত্তরা দিয়াবাড়ী": "Uttara Diabari",
  "উথুলী": "Uthuli",
  "এয়ারপোর্ট": "Airport",
  "ওয়ার্ক সপ": "Workshop",
  "কচুক্ষেত": "Kochukhet",
  "কদমতলী": "Kadamtali",
  "কমলাপুর": "Kamalapur",
  "কমলাপুর (পীরজঙ্গী মাজার)": "Kamalapur (Pirjongi Mazar)",
  "কমলাপুর ষ্টেশন": "Kamalapur Station",
  "কলাবাগান": "Kalabagan",
  "কলেজ গেইট": "College Gate",
  "কল্যাণপুর": "Kalyanpur",
  "কাঁচপুর": "Kanchpur",
  "কাঁচপুর ব্রীজ": "Kanchpur Bridge",
  "কাওরান বাজার": "Kawran Bazar",
  "কাকরাইল": "Kakrail",
  "কাকলী": "Kakoli",
  "কাজীপাড়া": "Kazipara",
  "কাটাবন": "Katabon",
  "কাপাসিয়া": "Kapasia",
  "কামরাঙ্গীরচর (বেড়ীবাঁধ)": "Kamrangirchar (Beribadh)",
  "কামার পাড়া": "Kamarpara",
  "কালশী": "Kalshi",
  "কালশী মোড়": "Kalshi More",
  "কালাপানি": "Kalapani",
  "কালামপুর": "Kalampur",
  "কালিয়াকৈর": "Kaliakair",
  "কাশেমপুর": "Kashempur",
  "কুড়িল": "Kuril",
  "কুড়িল ফ্লাইওভার": "Kuril Flyover",
  "কুড়িল বিশ্বরোড": "Kuril Bishwaroad",
  "কুর্মিটোলা জেনারেল হাসপাতাল": "Kurmitola General Hospital",
  "কেরানীগঞ্জ": "Keraniganj",
  "কেরানীগঞ্জ (নতুন জেলখানা)": "Keraniganj (New Jail)",
  "কোণাখোলা বাজার": "Konakhola Bazar",
  "কোনাখোলা": "Konakhola",
  "কোনাবাড়ী": "Konabari",
  "কোমরগঞ্জ": "Komorganj",
  "ক্যান্টনমেন্ট সিগন্যাল গেট": "Cantonment Signal Gate",
  "খাইস্যাখালী বৌড়বাঁধ": "Khaisyakhali Bourbandh",
  "খামারবাড়ি মোড়": "Khamarbari More",
  "খারশুর": "Kharshur",
  "খাশিয়াখালী বেঁড়িবাঁধ": "Khashiakhali Beribandh",
  "খিলক্ষেত": "Khilkhet",
  "খিলগাঁও খিদমাহ হাসপাতাল": "Khilgaon Khidmah Hospital",
  "খিলগাঁও ফ্লাইওভার": "Khilgaon Flyover",
  "খিলগাঁও রেলগেট": "Khilgaon Rail Gate",
  "খিলগাও তালতলা": "Khilgaon Taltola",
  "খেজুর বাগান": "Khejur Bagan",
  "গাজীপুর": "Gazipur",
  "গাজীপুর চৌরাস্তা": "Gazipur Chourasta",
  "গাবতলী": "Gabtoli",
  "গাবতলী ব্রীজ পাড়": "Gabtoli Bridge Par",
  "গুলশান-১": "Gulshan-1",
  "গুলশান-২": "Gulshan-2",
  "গুলিস্তান (ফুলবাড়িয়া)": "Gulistan (Fulbaria)",
  "গুলিস্তান মোড়": "Gulistan More",
  "গুলিস্থান": "Gulistan",
  "গুলিস্থান (হানিফ ফ্লাইওভার)": "Gulistan (Hanif Flyover)",
  "গোলাপশাহ মাজার": "Golapshah Mazar",
  "গোলাপশাহ মাজার (ফুলবাড়ীয়া)": "Golapshah Mazar (Fulbaria)",
  "ঘাটার চর": "Ghatar Char",
  "ঘাটারচর": "Ghatarchar",
  "চন্দ্রা": "Chandra",
  "চাঁনখারপুল": "Chankharpul",
  "চানখারপুর": "Chankharpur",
  "চাষাঢ়া বাসস্ট্যান্ড": "Chashara Bus Stand",
  "চিড়িয়াখানা": "Chiriakhana (Zoo)",
  "চুন কুটিয়া": "Chun Kutia",
  "চুনকুটিয়া বাজার": "Chunkutia Bazar",
  "চেরাগআলী": "Cheragali",
  "চৌরাস্তা": "Chourasta",
  "জগন্নাথ বিশ্ববিদ্যালয়": "Jagannath University",
  "জনপথ": "Jonopath",
  "জয়দেবপুর চৌঃ": "Joydebpur Chourasta",
  "জসীমউদ্দিন": "Jasimuddin",
  "জাপান গার্ডেন সিটি": "Japan Garden City",
  "জিগাতলা": "Jigatola",
  "জিঞ্জিরা": "Jinjira",
  "জিপিও": "GPO",
  "জিরানী": "Zirani",
  "জিরানী বাজার": "Zirani Bazar",
  "জিরাব": "Jirab",
  "জিরাবো": "Jirabo",
  "জিল্লুর রহমান ফ্লাইওভার": "Zillur Rahman Flyover",
  "জুরাইন": "Jurain",
  "ঝিগাতলা": "Jhigatola",
  "টংঙ্গী (বাস্তুহারা)": "Tongi (Bastuhara)",
  "টংঙ্গী": "Tongi",
  "টকরপুর": "Tokorpur",
  "টঙ্গীবাজার": "Tongi Bazar",
  "টাউন হল": "Town Hall",
  "টিএন্ডটি": "T&T",
  "টিকরপুর": "Tikorpur",
  "টিকাটুলি": "Tikatuli",
  "টিটিপাড়া": "TT Para",
  "টিভি সেন্টার": "TV Center",
  "টেকনিক্যাল": "Technical",
  "ডেমরা": "Demra",
  "ডেমরা ব্রীজ": "Demra Bridge",
  "ডেমরা স্টাফ কোয়ার্টার": "Demra Staff Quarter",
  "ঢাকা কলেজ": "Dhaka College",
  "ঢাকা সিটি কলেজ": "Dhaka City College",
  "ঢাকেশ্বরী": "Dhakeshwari",
  "ঢাকেশ্বরী এতিমখানা": "Dhakeshwari Orphanage",
  "ঢাকেশ্বরী মন্দির": "Dhakeshwari Temple",
  "তাতি বাজার": "Tanti Bazar",
  "তারাবো বিশ্বরোড": "Tarabo Bishwaroad",
  "তিতুমীর কলেজ": "Titumir College",
  "ত্রিমোহনী": "Trimohoni",
  "দয়াগঞ্জ রোড": "Doyaganj Road",
  "দারুসসালাম": "Darussalam",
  "দিয়াবাড়ী": "Diabari",
  "দিয়াবাড়ী (বেড়িবাঁধ)": "Diabari (Beribadh)",
  "দিয়াবাড়ী চৌরাস্তা": "Diabari Chourasta",
  "দিয়াবাড়ী মোড়": "Diabari More",
  "দুয়ারীপাড়া": "Duaripara",
  "দৈনিক বাংলা": "Doinik Bangla",
  "ধউর": "Dhaur",
  "ধউর মোড়": "Dhaur More",
  "ধউর ব্রীজ": "Dhaur Bridge",
  "ধলেশ্বর": "Dholeshwar",
  "ধানমন্ডি": "Dhanmondi",
  "ধানমন্ডি-১৫": "Dhanmondi-15",
  "ধামরাই": "Dhamrai",
  "ধোপখোলা": "Dhopkhola",
  "নটর ডেম কলেজ": "Notre Dame College",
  "নতুন বাজার": "Notun Bazar",
  "নদ্দা": "Nadda",
  "নন্দন পার্ক": "Nandan Park",
  "নবাবগঞ্জ": "Nawabganj",
  "নবীনগর": "Nabinagar",
  "নবীনগর (সাভার)": "Nabinagar (Savar)",
  "নয়াবাজার": "Nayabazar",
  "নয়াবাজার (২নং বুড়িগঙ্গা সেতু)": "Nayabazar (2nd Buriganga Bridge)",
  "নরসিংহপুর": "Narasinghapur",
  "নর্দাপাড়া ব্রীজ": "Nordapara Bridge",
  "নাঃগঞ্জ লিংক রোড": "Narayanganj Link Road",
  "নাবিস্কো": "Nabisco",
  "নারায়নগঞ্জ": "Narayanganj",
  "নারায়নগঞ্জ চাষারা": "Narayanganj Chashara",
  "নিউ এয়ারপোর্ট": "New Airport",
  "নিউ মার্কেট": "New Market",
  "নীলক্ষেত": "Nilkhet",
  "নুতন বাজার": "Notun Bazar",
  "নৰ্দ্দা": "Nadda",
  "পলাশী": "Palashi",
  "পল্টন": "Paltan",
  "পল্লবী (মিরপুর-১২)": "Pallabi (Mirpur-12)",
  "পল্লবী (সিরামিক)": "Pallabi (Ceramic)",
  "পাটুরিয়া": "Paturia",
  "পীরজঙ্গী মাজার": "Pirjongi Mazar",
  "পূরবী": "Purobi",
  "পোস্তগোলা": "Postogola",
  "পোস্তগোলা ব্রীজ": "Postogola Bridge",
  "প্রগতি সরণী": "Pragati Sarani",
  "প্রশিকা": "Proshika",
  "প্রশিকা মোড়": "Proshika More",
  "প্রিয়াঙ্গন গেট": "Priyangan Gate",
  "প্রেসক্লাব": "Press Club",
  "ফকিরাপুল": "Fakirapool",
  "ফার্মগেট": "Farmgate",
  "ফুলবাড়ীয়া": "Fulbaria",
  "ফ্যান্টাসী": "Fantasy",
  "ফ্যান্টাসী কিংডম": "Fantasy Kingdom",
  "বকশিবাজার": "Bakshibazar",
  "বক্সনগর": "Boxnagar",
  "বঙ্গবন্ধু": "Bangabandhu",
  "বঙ্গবন্ধু এভিনিউ": "Bangabandhu Avenue",
  "বছিলা": "Bochila",
  "বনশ্রী": "Banasree",
  "বনশ্রী (মেরাদিয়া)": "Banasree (Meradia)",
  "বনানী": "Banani",
  "বরংগাইল": "Borangail",
  "বরপা": "Borpa",
  "বর্মী": "Bormi",
  "বসিলা": "Bosila",
  "বসিলা ব্রীজ": "Bosila Bridge",
  "বসুন্ধরা": "Bashundhara",
  "বাংলা কলেজ": "Bangla College",
  "বাংলা মটর": "Bangla Motor",
  "বাংলাদেশ ব্যাংক": "Bangladesh Bank",
  "বাইপাইল": "Baipail",
  "বাগমারা": "Bagmara",
  "বাঘের বাজার": "Bagher Bazar",
  "বাড্ডা": "Badda",
  "বাড্ডা লিংক রোড": "Badda Link Road",
  "বাড্ডা লিংক রোড/মধ্য বাড্ডা": "Badda Link Road / Modhho Badda",
  "বানিয়াজুড়ি": "Baniazuri",
  "বান্দুরা": "Bandura",
  "বাবু বাজার": "Babu Bazar",
  "বাবু বাজার ব্রীজ": "Babu Bazar Bridge",
  "বারুয়াখালী": "Baruakhali",
  "বালুঘাট": "Balughat",
  "বাস স্টপেজ": "Bus Stoppage",
  "বাসাবো": "Basabo",
  "বিজয় নগর": "Bijoy Nagar",
  "বিজয় স্মরণী": "Bijoy Sarani",
  "বিশ্বরোড": "Bishwaroad",
  "বুয়েট": "BUET",
  "বেজগাঁও চৌরাস্তা": "Bejgaon Chourasta",
  "বেড়ীবাঁধ": "Beribadh",
  "বেরাইদ": "Beraid",
  "বৈকালী হোটেল": "Boikali Hotel",
  "বোর্ড বাজার": "Board Bazar",
  "ভাওয়ার ভিটি (দক্ষিণ কেরানীগঞ্জ)": "Bhaowar Bhiti (South Keraniganj)",
  "ভাষানটেক": "Bhashantek",
  "ভিক্টোরিয়া পার্ক": "Victoria Park",
  "ভুলতা": "Bhulta",
  "ভুলতা (গাউছিয়া)": "Bhulta (Gawsia)",
  "মগবাজার": "Mogbazar",
  "মতিঝিল": "Motijheel",
  "মদনগঞ্জ": "Modonganj",
  "মদনপুর": "Modonpur",
  "মধ্য বাড্ডা": "Modhho Badda",
  "মন্থাহাজীর মোড়": "Monthahajir More",
  "মহাখালী": "Mohakhali",
  "মহাখালী আমতলী": "Mohakhali Amtoli",
  "মাওনা চৌরাস্তা": "Mawna Chourasta",
  "মাওয়া ফেরীঘাট": "Mawa Ferry Ghat",
  "মাওয়াঘাট": "Mawaghat",
  "মাজার রোড": "Mazar Road",
  "মাঝির কান্দা": "Majhir Kanda",
  "মানিক মিয়া": "Manik Mia",
  "মানিক মিয়া এভিনিউ": "Manik Mia Avenue",
  "মানিকগঞ্জ": "Manikganj",
  "মানিকদি (ইসিবি মোড়)": "Manikdi (ECB More)",
  "মালিবাগ": "Malibagh",
  "মালিবাগ চৌধুরীপাড়া": "Malibagh Chowdhurypara",
  "মাস্কট প্লাজা": "Mascot Plaza",
  "মিরপুর (চিড়িয়াখানা)": "Mirpur (Zoo)",
  "মিরপুর ডিওএইচ এস": "Mirpur DOHS",
  "মিরপুর থানা": "Mirpur Thana",
  "মিরপুর মাজার রোড": "Mirpur Mazar Road",
  "মিরপুর রূপনগর": "Mirpur Rupnagar",
  "মিরপুর সাড়ে ১১": "Mirpur Share Egaro (11.5)",
  "মিরপুর-১": "Mirpur-1",
  "মিরপুর-১০": "Mirpur-10",
  "মিরপুর-১১": "Mirpur-11",
  "মিরপুর-১০.৫": "Mirpur-10.5",
  "মিরপুর-১১.৫": "Mirpur-11.5",
  "মিরপুর-১২": "Mirpur-12",
  "মিরপুর-১৪": "Mirpur-14",
  "মিরপুর-২": "Mirpur-2",
  "মিরপুর-৬": "Mirpur-6",
  "মুগদা": "Mugda",
  "মেঘনা ঘাট": "Meghna Ghat",
  "মেয়র মোহাম্মদ হানিফ ফ্লাইওভার": "Mayor Mohammad Hanif Flyover",
  "মেরাদিয়া (নতুন রাস্তা)": "Meradia (New Road)",
  "মেরাদিয়া বাজার": "Meradia Bazar",
  "মোঃ জিল্লুর রহমান ফ্লাইওভার": "Md. Zillur Rahman Flyover",
  "মোঃপুর (জাপান গার্ডেন সিটি)": "Mohammadpur (Japan Garden City)",
  "মোঃপুর টাউন হল": "Mohammadpur Town Hall",
  "মোঃবাসস্ট্যান্ড": "Mohammadpur Bus Stand",
  "মোগড়া পাড়া": "Mograpara",
  "মোহাম্মদপুর": "Mohammadpur",
  "মোহাম্মদপুর (আসাদ এভিনিউ)": "Mohammadpur (Asad Avenue)",
  "মোহাম্মদপুর শিয়া মসজিদ": "Mohammadpur Shia Mosque",
  "মৌচাক": "Mouchak",
  "মৌচাক (ফ্লাইওভার)": "Mouchak (Flyover)",
  "মৎসভবন": "Matsya Bhaban",
  "যমুনা ফিউচার পার্ক": "Jamuna Future Park",
  "যাত্রাবাড়ী": "Jatrabari",
  "রাজমনি": "Rajmoni",
  "রাজলক্ষ্মী": "Rajlokkhi",
  "রাজাবাড়ী": "Rajabari",
  "রাজারবাগ": "Rajarbagh",
  "রাজেন্দ্রপুর": "Rajendrapur",
  "রাজেন্দ্রপুর চৌঃ": "Rajendrapur Chourasta",
  "রাজেন্দ্রপুর বাজার": "Rajendrapur Bazar",
  "রামপুরা": "Rampura",
  "রামপুরা (বনশ্রী)": "Rampura (Banasree)",
  "রামপুরা টিভি সেন্টার": "Rampura TV Center",
  "রামপুরা ব্রীজ": "Rampura Bridge",
  "রামের কান্দা": "Ramer Kanda",
  "রায়সাহেব বাজার": "Roy Shaheb Bazar",
  "রায়েরবাগ": "Rayerbagh",
  "রাসেল স্কয়ার": "Russell Square",
  "রুহিতপুর": "Ruhitpur",
  "রূপসী": "Rupashi",
  "রেইনবো": "Rainbow",
  "লিংক রোড": "Link Road",
  "শংকর": "Shankar",
  "শনির আখড়া": "Shonir Akhra",
  "শাপলা চত্বর": "Shapla Chattar",
  "শাহআলী মাজার": "Shah Ali Mazar",
  "শাহবাগ": "Shahbagh",
  "শিয়া মসজিদ": "Shia Mosque",
  "শিয়ালবাড়ী": "Shialbari",
  "শিশুমেলা": "Shishu Mela",
  "শুক্রাবাদ": "Shukrabad",
  "শুরগঞ্জ": "Shurganj",
  "শেওড়া": "Sheora",
  "শেওড়া পাড়া": "Sheora Para",
  "শেওড়া বাজার": "Sheora Bazar",
  "শেওড়াপাড়া": "Sheorapara",
  "শ্যামলী": "Shyamoli",
  "শ্যামলী রিং রোড": "Shyamoli Ring Road",
  "শ্রীপুর": "Sreepur",
  "সদরঘাট": "Sadarghat",
  "সদরঘাট ভিক্টোরিয়া": "Sadarghat Victoria",
  "সনি সিনেমা হল": "Sony Cinema Hall",
  "সফিপুর": "Safipur",
  "সাইনবোর্ড": "Signboard",
  "সাইন্সল্যাবঃ": "Science Lab",
  "সাতরাস্তা": "Satrasta",
  "সাভার": "Savar",
  "সায়েদাবাদ": "Sayedabad",
  "সিটি কলেজ": "City College",
  "সুলতানা কামাল ব্রীজ": "Sultana Kamal Bridge",
  "সৈনিক ক্লাব": "Sainik Club",
  "সৈয়দপুর": "Saidpur",
  "সোনারগাঁও": "Sonargaon",
  "সোনারগাঁও মোগড়া পাড়া": "Sonargaon Mograpara",
  "স্টাফ কোয়ার্টার": "Staff Quarter",
  "স্টাফরোড": "Staff Road",
  "স্টেডিয়াম": "Stadium",
  "হাইকোট": "High Court",
  "হাউজ বিল্ডিং": "House Building",
  "হানিফ ফ্লাইওভার": "Hanif Flyover",
  "হেমায়েতপুর": "Hemayetpur",
  "হোতাপাড়া": "Hotapara"
};
